package android.marshon.likequanmintv.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import android.marshon.likequanmintv.bean.ItemColumn;
import android.marshon.likequanmintv.bean.LiveCategory;
import android.marshon.likequanmintv.bean.PlayBean;

import android.marshon.likequanmintv.db.ItemColumnDao;
import android.marshon.likequanmintv.db.LiveCategoryDao;
import android.marshon.likequanmintv.db.PlayBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemColumnDaoConfig;
    private final DaoConfig liveCategoryDaoConfig;
    private final DaoConfig playBeanDaoConfig;

    private final ItemColumnDao itemColumnDao;
    private final LiveCategoryDao liveCategoryDao;
    private final PlayBeanDao playBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemColumnDaoConfig = daoConfigMap.get(ItemColumnDao.class).clone();
        itemColumnDaoConfig.initIdentityScope(type);

        liveCategoryDaoConfig = daoConfigMap.get(LiveCategoryDao.class).clone();
        liveCategoryDaoConfig.initIdentityScope(type);

        playBeanDaoConfig = daoConfigMap.get(PlayBeanDao.class).clone();
        playBeanDaoConfig.initIdentityScope(type);

        itemColumnDao = new ItemColumnDao(itemColumnDaoConfig, this);
        liveCategoryDao = new LiveCategoryDao(liveCategoryDaoConfig, this);
        playBeanDao = new PlayBeanDao(playBeanDaoConfig, this);

        registerDao(ItemColumn.class, itemColumnDao);
        registerDao(LiveCategory.class, liveCategoryDao);
        registerDao(PlayBean.class, playBeanDao);
    }
    
    public void clear() {
        itemColumnDaoConfig.clearIdentityScope();
        liveCategoryDaoConfig.clearIdentityScope();
        playBeanDaoConfig.clearIdentityScope();
    }

    public ItemColumnDao getItemColumnDao() {
        return itemColumnDao;
    }

    public LiveCategoryDao getLiveCategoryDao() {
        return liveCategoryDao;
    }

    public PlayBeanDao getPlayBeanDao() {
        return playBeanDao;
    }

}
